server:
  port: 8081
  servlet:
    context-path: /app

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_market
#    username:
#    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

#logging:
#  level:
#    root: info
#    org:
#      springframework:
#        web: debug
#        hibernate: error
#        data: error
#  file:
#    path: logs
#  pattern:
#    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
#    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'
